### ISSUE TITLE
Update simplemde.min.js?

### ISSUE THREAD

**Issue by d9su** [KHN190/simplemde-rails#1]
It seems the js file is very old and has some useless console logging. Updating it should solve the issue. 

Also might wanna update the link in the readme to:
https://github.com/sparksuite/simplemde-markdown-editor

Thoughts?

**Comment by bhavyanshu** [comment]
@KHN190 
I am facing the same issue. Please push updated version of simplemde.min.js. Thanks!

**Comment by KHN190** [comment]
@bhavyanshu I have updated scripts to the latest simplende.min.js

Actually this gem is quite straight forward, you can just download the js from simplemde and replace them which is located in /vendor. Or if you are using Rails 5, put them in /app/assets and require them in application.js

**Comment by KHN190** [comment]
Now require the gem in Gemfile:
```
gem 'simplemde-rails', git: 'https://github.com/KHN190/simplemde-rails'
# or
gem 'simplemde-rails', '~> 1.11.2'
```

**Comment by d9su** [comment]
Thanks for the quick update! I referenced this repo in https://github.com/sferik/rails_admin/pull/2949 for its convenience :P

**Comment by bhavyanshu** [comment]
@KHN190 I appreciate you getting back so quickly and fixing it. Thanks a lot!
