### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jrdnbwmn** [KHN190/simplemde-rails#3]
I did the following:

1. Added `gem 'simplemde-rails'` to Gemfile
2. Executed `bundle install`
3. Executed `rails g simplemde:install`
4. Included the assets with `//= require simplemde.min` and `@import "simplemde.min";` and checked to make sure they were there.
5. Added `var simplemde = new SimpleMDE();` to my JS and made sure it was there.

It doesn't seem to be working though—it doesn't change anything about `textarea`s on any pages.

Is there anything else I need to do? I'm pretty new to Rails, so I greatly appreciate any help. 😁

**Comment by KHN190** [comment]
@jrdnbwmn Is your CSS converted to SASS before it's imported?
Otherwise you'd like to try just add these to your template
```
<link rel="stylesheet" href="assets/simplemde.min.css">
<script src="assets/simplemde.min.js"></script>
```

**Comment by jrdnbwmn** [comment]
I added 

```
<link rel="stylesheet" href="assets/simplemde.min.css">
<script src="assets/simplemde.min.js"></script>
```

to my template, but that didn't change anything.

I've opened the DOM Inspector in my browser and made sure all the assets were there—they are. 

I've tried this on a fresh rails install just to make sure. This is what a `textarea` looks like (as you can see, the markdown editor isn't showing up):

<img width="268" alt="screen shot 2018-04-10 at 4 17 35 pm" src="https://user-images.githubusercontent.com/4484045/38586382-bba14dd6-3cda-11e8-8134-e4135209706b.png">

**Comment by KHN190** [comment]
@jrdnbwmn Would you mind sending me a copy of your fresh rails demo to me? My email: knh190 at hotmail.com

**Comment by jrdnbwmn** [comment]
I will do that, thank you for being so helpful!

**Comment by jrdnbwmn** [comment]
It was actually a Turbolinks issue: https://stackoverflow.com/questions/36110789/rails-5-how-to-use-document-ready-with-turbo-links?noredirect=1&lq=1
